homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.8986
  longitude: -8.4958
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 27
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Dublin
  packages: !include_dir_named packages    

#  configuration:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret dns_host
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Enabled support for tracking state changes over time.
recorder:
  purge_keep_days: 2

# Track the sun
sun:

media_player:

zone:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  radius: 200

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

shopping_list:

influxdb:
  username: home-assistant
  password: !secret influxdb_password
