hue:
  bridges:
    - host: 192.168.0.100

homeassistant:
  customize:
    light.shed:
      icon: mdi:garage-open
    light.indian_lamp:
      icon: mdi:lava-lamp
    light.front_door:
      icon: mdi:door
    light.sofa_light:
      icon: mdi:sofa
    light.wine_rack_lamp:
      icon: mdi:glass-tulip
    light.downstairs_hall_lamp:
      icon: mdi:lamp
    light.landing_light:
      icon: mdi:ceiling-light
    light.attic_stairs_light:
      icon: mdi:ceiling-light
