###############################################################################
#
#
#
###############################################################################
#homeassistant:
#  customize:


# hide Multi Sensor Xtra Stuff
#
# hidden in customize_glob

###############################################################################
# Sensors
###############################################################################
sensor:
  - platform: yr
    name: Weather
    monitored_conditions:
      - temperature
      - cloudiness
      - precipitation
      - windSpeed
      - pressure
  - platform: google_travel_time
    api_key: !secret google_api_key
    origin: device_tracker.matts_phone_matts_phone
    destination: zone.home
    name: 'Time to Home'
  - platform: google_travel_time
    api_key: !secret google_api_key
    origin: device_tracker.matts_phone_matts_phone
    destination: Avenue 4000, Cork Airport Business Park, Cork
    name: 'Time to Work'
  - platform: template
    sensors:
      kettle_total_kw:
        value_template: '{{ states.switch.kettle.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kW'
        friendly_name: 'Kettle Total Power Usage'
      kettle_current_w:
        value_template: '{{ states.switch.kettle.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: 'W'
        friendly_name: 'Kettle Current Power Usage'
      mirror_lights_total_kw:
        value_template: '{{ states.switch.mirror_lights.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kW'
        friendly_name: 'Mirror Lights Total Power Usage'
      mirror_lights_current_w:
        value_template: '{{ states.switch.mirror_lights.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: 'W'
        friendly_name: 'Mirror Lights Current Power Usage'
  - platform: rest
    resource: http://192.168.0.100/api/lDIhhTHDO3mBDzQKsxNuJfGyIhcA-o3eLVAbyVjK/sensors/11
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: Gate Lux
  - platform: rest
    resource: http://192.168.0.100/api/lDIhhTHDO3mBDzQKsxNuJfGyIhcA-o3eLVAbyVjK/sensors/19
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: Attic Hall Lux
  - platform: rest
    resource: http://192.168.0.100/api/lDIhhTHDO3mBDzQKsxNuJfGyIhcA-o3eLVAbyVjK/sensors/25
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: Shed Lux
  - platform: rest
    resource: http://192.168.0.100/api/lDIhhTHDO3mBDzQKsxNuJfGyIhcA-o3eLVAbyVjK/sensors/27
    value_template: '{{ value_json.state.status }}'
    name: 'Gate Motion'
  - platform: rest
    resource: http://192.168.0.100/api/lDIhhTHDO3mBDzQKsxNuJfGyIhcA-o3eLVAbyVjK/sensors/28
    value_template: '{{ value_json.state.status }}'
    name: 'Shed Motion'
  ################################################
  ## History Stats
  ################################################  
  - platform: history_stats
    name: TV On today
    entity_id: group.livingroom_tv_ips
    state: 'home'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: TV On this week
    entity_id: group.livingroom_tv_ips
    state: 'home'
    type: time
    start: '{{ as_timestamp(now().replace(hour=0).replace(minute=0).replace(second=0)) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Heating ON today
    entity_id: sensor.downstairs_thermostat_hvac_state
    state: 'heating'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Heating ON yesterday
    entity_id: sensor.downstairs_thermostat_hvac_state
    state: 'heating'
    type: time
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration: 
      hours: 24
  - platform: history_stats
    name: Heating ON this week
    entity_id: sensor.downstairs_thermostat_hvac_state
    state: 'heating'
    type: time
    start: '{{ as_timestamp(now().replace(hour=0).replace(minute=0).replace(second=0)) - now().weekday() * 86400 }}'
    end: '{{ now() }}' 
  - platform: history_stats
    name: Heating ON last week
    entity_id: sensor.downstairs_thermostat_hvac_state
    state: 'heating'
    type: time
    end: '{{ as_timestamp(now().replace(hour=0).replace(minute=0).replace(second=0)) - now().weekday() * 86400 }}'
    duration:
      days: 7
  - platform: history_stats
    name: Heating ON accumulated
    entity_id: sensor.downstairs_thermostat_hvac_state
    state: 'heating'
    type: time
#    start: '{{ now().replace(year=2016) }}'
    start: '{{ 0 }}'
    end: '{{ now() }}'
  ################################################
  ## MQTT
  ################################################
  - platform: mqtt
    state_topic: 'wemosd1mini/baby_room/SENSOR'
    name: 'Moons Room - Temperature'
    unit_of_measurement: 'C'
    value_template: '{{ value_json.BME280.Temperature }}'
  - platform: mqtt
    state_topic: 'wemosd1mini/baby_room/SENSOR'
    name: 'Moons Room - Humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.BME280.Humidity }}'
  - platform: mqtt
    state_topic: 'wemosd1mini/kitchen/SENSOR'
    name: 'Kitchen - Temperature'
    unit_of_measurement: 'C'
    value_template: '{{ value_json.BME280.Temperature }}'
  - platform: mqtt
    state_topic: 'wemosd1mini/kitchen/SENSOR'
    name: 'Kitchen - Humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.BME280.Humidity }}'


################################################
## Binary Sensors
################################################
# Sensor to monitor if a devices power usage drops below its running state.
# Uses: Alert when drier has finished. Monitor TV usage (when above standby consumption)
binary_sensor:
#  - platform: template
#    sensors:
#      drier:
#        value_template: >-
#          {%- if states.switch.drier.attributes["Current consumption"] | replace(" W", "") | float %}
#              {{ states.switch.drier.attributes["Current consumption"] | replace(" W", "") | float  > 1.0}}
#          {%  else %}
#              0
#          {%- endif %}
#        friendly_name: 'Is drier running?'
# Uses: Trigger default lighting when it's actually dark, rathen than sunset.
  - platform: template
    sensors:
      bright_outside:
        value_template: "{{ states('sensor.gate_lux')|float > 11000 }}"
        device_class: light
        friendly_name: "Bright Outside?"


################################################
## Switches
################################################

switch:
  - platform: tplink
    host: 192.168.0.10
  - platform: tplink
    host: 192.168.0.14
  - platform: tplink
    host: 192.168.0.18
  - platform: mqtt
    name: "Back lights"
    command_topic: "sonoff/outside_lights_back/cmnd/POWER"
    state_topic: "sonoff/outside_lights_back/RESULT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    value_template: "{{ value_json.POWER }}"

################################################
## Cameras
################################################
camera:
  - platform: generic
    name: Kitchen Camera
    still_image_url: http://192.168.0.25/tmpfs/auto.jpg
    username: admin
    password: !secret camera_password
  - platform: ffmpeg
    input: !secret front_camera_rtsp
    name: Driveway Camera
#    extra_arguements: -q:v 2

