###############################################################################
#
#
#
###############################################################################
homeassistant:
  customize:
    sensor.gate_motion:
      entity_picture: /local/Gate.JPG

# hide Multi Sensor Xtra Stuff
#
# hidden in customize_glob

###############################################################################
# Sensors
###############################################################################
sensor:
  - platform: yr
    name: Weather
    monitored_conditions:
      - temperature
      - cloudiness
      - precipitation
      - windSpeed
      - pressure
  - platform: google_travel_time
    api_key: !secret google_api_key
    origin: device_tracker.mqtt_matts_phone
    destination: zone.home
    scan_interval: 600
    name: 'Time to Home'
  - platform: google_travel_time
    api_key: !secret google_api_key
    origin: device_tracker.mqtt_matts_phone
    destination: Avenue 4000, Cork Airport Business Park, Cork
    scan_interval: 600
    name: 'Time to Work'
  - platform: template
    sensors:
      kettle_total_kw:
        value_template: '{{ states.switch.kettle.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kW'
        friendly_name: 'Kettle Total Power Usage'
      kettle_current_w:
        value_template: '{{ states.switch.kettle.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: 'W'
        friendly_name: 'Kettle Current Power Usage'
      livingroom_tv_total_kw:
        value_template: '{{ states.switch.living_room_tv.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kW'
        friendly_name: 'TV Total Power Usage'
      livingroom_tv_current_w:
        value_template: '{{ states.switch.living_room_tv.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: 'W'
        friendly_name: 'TV Current Power Usage'
  - platform: rest
    resource: http://192.168.0.100/api/lDIhhTHDO3mBDzQKsxNuJfGyIhcA-o3eLVAbyVjK/sensors/11
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: Gate Lux
  - platform: rest
    resource: http://192.168.0.100/api/lDIhhTHDO3mBDzQKsxNuJfGyIhcA-o3eLVAbyVjK/sensors/19
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: Attic Hall Lux
  - platform: rest
    resource: http://192.168.0.100/api/lDIhhTHDO3mBDzQKsxNuJfGyIhcA-o3eLVAbyVjK/sensors/25
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: Shed Lux
  - platform: rest
    resource: http://192.168.0.100/api/lDIhhTHDO3mBDzQKsxNuJfGyIhcA-o3eLVAbyVjK/sensors/27
    value_template: '{{ value_json.state.status }}'
    name: 'Gate Motion'
  - platform: rest
    resource: http://192.168.0.100/api/lDIhhTHDO3mBDzQKsxNuJfGyIhcA-o3eLVAbyVjK/sensors/28
    value_template: '{{ value_json.state.status }}'
    name: 'Shed Motion'
  - platform: rest
    resource: http://192.168.0.100/api/lDIhhTHDO3mBDzQKsxNuJfGyIhcA-o3eLVAbyVjK/sensors/9
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Outside Temperature'
  - platform: rest
    resource: http://192.168.0.100/api/lDIhhTHDO3mBDzQKsxNuJfGyIhcA-o3eLVAbyVjK/sensors/17
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Attic Hall Temperature'
  - platform: rest
    resource: http://192.168.0.100/api/lDIhhTHDO3mBDzQKsxNuJfGyIhcA-o3eLVAbyVjK/sensors/23
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Shed Temperature'

  ################################################
  ## History Stats
  ################################################  
  - platform: history_stats
    name: TV On today
    entity_id: group.livingroom_tv_ips
    state: 'home'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: TV On this week
    entity_id: group.livingroom_tv_ips
    state: 'home'
    type: time
    start: '{{ as_timestamp(now().replace(hour=0).replace(minute=0).replace(second=0)) - now().weekday() * 86400 }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Heating ON today
    entity_id: switch.heating_on_off
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Heating ON yesterday
    entity_id: switch.heating_on_off
    state: 'on'
    type: time
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration: 
      hours: 24
  - platform: history_stats
    name: Heating ON this week
    entity_id: switch.heating_on_off
    state: 'on'
    type: time
    start: '{{ as_timestamp(now().replace(hour=0).replace(minute=0).replace(second=0)) - now().weekday() * 86400 }}'
    end: '{{ now() }}' 
  - platform: history_stats
    name: Heating test
    entity_id: switch.heating_on_off
    state: 'on'
    type: time
    end: '{{ now() }}'
    duration:
      days: 30
  - platform: statistics
    entity_id: switch.heating_on_off


  ################################################
  ## MQTT
  ################################################
  - platform: mqtt
    state_topic: '/ESPEasy_MasterBedroom/BME280/Temperature'
    name: 'Master Bedroom - Temperature'
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: '/ESPEasy_MasterBedroom/BME280/Humidity'
    name: 'Master Bedroom - Humidity'
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: '/ESPEasy_FiasRoom/BME280/Temperature'
    name: 'Fias Bedroom - Temperature'
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: '/ESPEasy_FiasRoom/BME280/Humidity'
    name: 'Fias Bedroom - Humidity'
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: '/ESPEasy_Office/BMP280/Temperature'
    name: 'Office - Temperature'
    unit_of_measurement: "°C"
  - platform: mqtt
    state_topic: '/ESPEasy_Office/BMP280/Pressure'
    name: 'Office - Pressure'
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: '/ESPEasy_Livingroom/BMP280/Temperature'
    name: 'Livingroom - Temperature'
    unit_of_measurement: "°C"
    json_attributes:
      - Temperature
  - platform: mqtt
    state_topic: '/ESPEasy_Livingroom/BMP280/Pressure'
    name: 'Livingroom - Pressure'
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: 'wemosd1mini/kitchen/SENSOR'
    name: 'Kitchen - Temperature'
    unit_of_measurement: "°C"
    value_template: '{{ value_json.BME280.Temperature }}'
  - platform: mqtt
    state_topic: 'wemosd1mini/kitchen/SENSOR'
    name: 'Kitchen - Humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.BME280.Humidity }}'


################################################
## Binary Sensors
################################################
# Sensor to monitor if a devices power usage drops below its running state.
# Uses: Alert when drier has finished. Monitor TV usage (when above standby consumption)
binary_sensor:
#  - platform: template
#    sensors:
#      drier:
#        value_template: >-
#          {%- if states.switch.drier.attributes["Current consumption"] | replace(" W", "") | float %}
#              {{ states.switch.drier.attributes["Current consumption"] | replace(" W", "") | float  > 1.0}}
#          {%  else %}
#              0
#          {%- endif %}
#        friendly_name: 'Is drier running?'
# Uses: Trigger default lighting when it's actually dark, rathen than sunset.
  - platform: template
    sensors:
      bright_outside:
        value_template: "{{ states('sensor.gate_lux')|float > 11000 }}"
        device_class: light
        friendly_name: "Bright Outside?"
      proper_dark_outside:
        value_template: "{{ states('sensor.gate_lux')|float < 1000 }}"
        device_class: light
        friendly_name: "Proper dark outside"


################################################
## Switches
################################################

switch:
  - platform: tplink
    host: 192.168.0.109
  - platform: tplink
    host: 192.168.0.124
  - platform: tplink
    host: 192.168.0.235
  - platform: mqtt
    name: "Back lights"
    command_topic: "sonoff/outside_lights_back/cmnd/POWER"
    state_topic: "sonoff/outside_lights_back/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
#    value_template: "{{ value_json.POWER }}"
  - platform: mqtt
    name: "Heating on off"
    command_topic: "sonoff/boiler_switch/cmnd/POWER"
    state_topic: "sonoff/boiler_switch/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    retain: false
  - platform: mqtt
    name: "Master Bedroom cold"
    command_topic: "heating/master_bedroom_cold"
    qos: 1
    payload_on: "true"
    payload_off: "false"
    retain: true
  - platform: mqtt
    name: "Fias Bedroom cold"
    command_topic: "heating/fias_bedroom_cold"
    qos: 1
    payload_on: "true"
    payload_off: "false"
    retain: true
  - platform: mqtt
    name: "Living room cold"
    command_topic: "heating/living_room_cold"
    qos: 1
    payload_on: "true"
    payload_off: "false"
    retain: true
  - platform: mqtt
    name: "20 minute boost"
    command_topic: "heating/boost20"
    qos: 1
    payload_on: "true"
    payload_off: "false"
    retain: true

################################################
## Cameras
################################################
camera:
  - platform: generic
    name: Kitchen Camera Image
    still_image_url: http://192.168.0.25/tmpfs/auto.jpg
    username: admin
    password: !secret camera_password
  - platform: ffmpeg
    input: rtsp://admin:Matches1!@192.168.0.25/11
    name: Kitchen Camera
  - platform: ffmpeg
    input: !secret front_camera_rtsp
    name: Driveway Camera
#    extra_arguements: -q:v 2

