group:
  switches:
    name: Switches
    entities:
      - switch.attic_lamp
      - switch.kettle
      - switch.mirror_lights
      - switch.back_lights

homeassistant:
  customize:
    switch.kettle:
      icon: mdi:kettle
    switch.attic_lamp:
      icon: mdi:lamp
    switch.mirror_lights:
      icon: mdi:glassdoor
