group:
  switches:
    name: Switches
    entities:
      - switch.attic_lamp
      - switch.kettle
#      - switch.bedroom_fan
      - switch.back_lights

homeassistant:
  customize:
    switch.kettle:
      icon: mdi:kettle
    switch.attic_lamp:
      icon: mdi:lamp
#    switch.mirror_lights:
#      icon: mdi:glassdoor
#    switch.bedroom_fan:
#      icon: mdi:fan
    switch.back_lights:
      icon: mdi:lightbulb-on-outline
    switch.livingroom_tv:
      icon: mdi:television
